theme: jekyll-theme-cayman
title: Blurry
description: The browser extension to blur unwanted contents on any webpage with the customised blur level.
show_downloads: https://github.com/doubledudes/blurry/blob/master/blurry-extension.zip
google_analytics: 
